// A small curated set, not the full Unicode emoji database — enough to make
// the `:` trigger useful without shipping a multi-thousand-entry index.
export const EMOJI_LIST: { name: string; char: string }[] = [
  { name: "smile", char: "😄" },
  { name: "laughing", char: "😆" },
  { name: "wink", char: "😉" },
  { name: "heart", char: "❤️" },
  { name: "thumbsup", char: "👍" },
  { name: "thumbsdown", char: "👎" },
  { name: "fire", char: "🔥" },
  { name: "star", char: "⭐" },
  { name: "sparkles", char: "✨" },
  { name: "rocket", char: "🚀" },
  { name: "tada", char: "🎉" },
  { name: "warning", char: "⚠️" },
  { name: "check", char: "✅" },
  { name: "x", char: "❌" },
  { name: "eyes", char: "👀" },
  { name: "thinking", char: "🤔" },
  { name: "bulb", char: "💡" },
  { name: "memo", char: "📝" },
  { name: "pushpin", char: "📌" },
  { name: "calendar", char: "📅" },
  { name: "clock", char: "🕐" },
  { name: "wave", char: "👋" },
  { name: "clap", char: "👏" },
  { name: "pray", char: "🙏" },
  { name: "100", char: "💯" },
  { name: "coffee", char: "☕" },
  { name: "bug", char: "🐛" },
  { name: "book", char: "📚" },
  { name: "target", char: "🎯" },
  { name: "hourglass", char: "⏳" },
];
